/*

    Setup inicial

*/

-- Permitiendo idempotencia a través de un refresh destructivo
DROP SCHEMA IF EXISTS normalization CASCADE;
CREATE SCHEMA normalization;

/*

    Tabla: city

*/

CREATE TABLE normalization.city (
    id BIGSERIAL PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL UNIQUE
);

INSERT INTO normalization.city (nombre)
SELECT DISTINCT city
FROM cleaning.food_inspections
WHERE city IS NOT NULL;

/*

    Tabla: violation

*/
CREATE TABLE normalization.violation (
    id BIGSERIAL PRIMARY KEY,
    code SMALLINT NOT NULL UNIQUE,
    description VARCHAR(200) NOT NULL UNIQUE
);

INSERT INTO normalization.violation (code, description)
VALUES
    (1,	'SOURCE SOUND CONDITION, NO SPOILAGE, FOODS PROPERLY LABELED, SHELLFISH TAGS IN PLACE'),
    (2,	'CITY OF CHICAGO FOOD SERVICE SANITATION CERTIFICATE'),
    (3,	'MANAGEMENT, FOOD EMPLOYEE AND CONDITIONAL EMPLOYEE; KNOWLEDGE, RESPONSIBILITIES AND REPORTING'),
    (4,	'PROPER USE OF RESTRICTION AND EXCLUSION'),
    (5,	'PROCEDURES FOR RESPONDING TO VOMITING AND DIARRHEAL EVENTS'),
    (6,	'PROPER EATING, TASTING, DRINKING, OR TOBACCO USE'),
    (7,	'WASH AND RINSE WATER: CLEAN AND PROPER TEMPERATURE'),
    (8,	'SANITIZING RINSE FOR EQUIPMENT AND UTENSILS'),
    (9,	'WATER SOURCE: SAFE, HOT & COLD UNDER CITY PRESSURE'),
    (10, 'SEWAGE AND WASTE WATER DISPOSAL, NO BACK SIPHONAGE, CROSS  CONNECTION AND/OR BACK FLOW'),
    (11, 'ADEQUATE NUMBER, CONVENIENT, ACCESSIBLE, DESIGNED, AND MAINTAINED'),
    (12, 'HAND WASHING FACILITIES: WITH SOAP AND SANITARY HAND DRYING DEVICES, CONVENIENT AND ACCESSIBLE TO FOOD PREP AREA'),
    (13, 'NO EVIDENCE OF RODENT OR INSECT INFESTATION, NO BIRDS, TURTLES OR OTHER ANIMALS'),
    (14, 'PREVIOUS SERIOUS VIOLATION CORRECTED'),
    (15, 'FOOD SEPARATED AND PROTECTED'),
    (16, 'FOOD PROTECTED DURING STORAGE, PREPARATION, DISPLAY, SERVICE AND TRANSPORTATION'),
    (17, 'POTENTIALLY HAZARDOUS FOOD PROPERLY THAWED'),
    (18, 'NO EVIDENCE OF RODENT OR INSECT OUTER OPENINGS PROTECTED/RODENT PROOFED, A WRITTEN LOG SHALL BE MAINTAINED AVAILABLE TO THE INSPECTORS'),
    (19, 'OUTSIDE GARBAGE WASTE GREASE AND STORAGE AREA; CLEAN, RODENT PROOF, ALL CONTAINERS COVERED'),
    (20, 'INSIDE CONTAINERS OR RECEPTACLES: ADEQUATE NUMBER, PROPERLY COVERED AND INSECT/RODENT PROOF'),
    (21, 'PROPER HOT HOLDING TEMPERATURES'),
    (22, 'DISH MACHINES: PROVIDED WITH ACCURATE THERMOMETERS, CHEMICAL TEST KITS AND SUITABLE GAUGE COCK'),
    (23, 'PROPER DATE MARKING AND DISPOSITION'),
    (24, 'TIME AS A PUBLIC HEALTH CONTROL; PROCEDURES & RECORDS'),
    (25, 'CONSUMER ADVISORY PROVIDED FOR RAW/UNDERCOOKED FOOD'),
    (26, 'ADEQUATE NUMBER, CONVENIENT, ACCESSIBLE, PROPERLY DESIGNED AND INSTALLED'),
    (27, 'TOILET ROOMS ENCLOSED CLEAN, PROVIDED WITH HAND CLEANSER, SANITARY HAND DRYING DEVICES AND PROPER WASTE RECEPTACLES'),
    (28, 'INSPECTION REPORT SUMMARY DISPLAYED AND VISIBLE TO ALL CUSTOMERS'),
    (29, 'PREVIOUS MINOR VIOLATION(S) CORRECTED'),
    (30, 'FOOD IN ORIGINAL CONTAINER, PROPERLY LABELED: CUSTOMER ADVISORY POSTED AS NEEDED'),
    (31, 'CLEAN MULTI-USE UTENSILS AND SINGLE SERVICE ARTICLES PROPERLY STORED'),
    (32, 'FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DESIGNED, CONSTRUCTED AND MAINTAINED'),
    (33, 'FOOD AND NON-FOOD CONTACT EQUIPMENT UTENSILS CLEAN, FREE OF ABRASIVE DETERGENTS'),
    (34, 'FLOORS: CONSTRUCTED PER CODE, CLEANED, GOOD REPAIR, COVING INSTALLED, DUST-LESS CLEANING METHODS USED'),
    (35, 'WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTED PER CODE: GOOD REPAIR, SURFACES CLEAN AND DUST-LESS CLEANING METHODS'),
    (36, 'LIGHTING: REQUIRED MINIMUM FOOT-CANDLES OF LIGHT PROVIDED, FIXTURES SHIELDED'),
    (37, 'TOILET ROOM DOORS SELF CLOSING: DRESSING ROOMS WITH LOCKERS PROVIDED: COMPLETE SEPARATION FROM LIVING/SLEEPING QUARTERS'),
    (38, 'VENTILATION: ROOMS AND EQUIPMENT VENTED AS REQUIRED: PLUMBING: INSTALLED AND MAINTAINED'),
    (39, 'CONTAMINATION PREVENTED DURING FOOD PREPARATION, STORAGE & DISPLAY'),
    (40, 'PERSONAL CLEANLINESS'),
    (41, 'PREMISES MAINTAINED FREE OF LITTER, UNNECESSARY ARTICLES, CLEANING  EQUIPMENT PROPERLY STORED'),
    (42, 'APPROPRIATE METHOD OF HANDLING OF FOOD (ICE) HAIR RESTRAINTS AND CLEAN APPAREL WORN'),
    (43, 'FOOD (ICE) DISPENSING UTENSILS, WASH CLOTHS PROPERLY STORED'),
    (44, 'UTENSILS, EQUIPMENT & LINENS: PROPERLY STORED, DRIED, & HANDLED'),
    (45, 'SINGLE-USE/SINGLE-SERVICE ARTICLES: PROPERLY STORED & USED'),
    (46, 'GLOVES USED PROPERLY'),
    (47, 'FOOD & NON-FOOD CONTACT SURFACES CLEANABLE, PROPERLY DESIGNED, CONSTRUCTED & USED'),
    (48, 'WAREWASHING FACILITIES: INSTALLED, MAINTAINED & USED; TEST STRIPS'),
    (49, 'NON-FOOD/FOOD CONTACT SURFACES CLEAN'),
    (50, 'HOT & COLD WATER AVAILABLE; ADEQUATE PRESSURE'),
    (51, 'PLUMBING INSTALLED; PROPER BACKFLOW DEVICES'),
    (52, 'SEWAGE & WASTE WATER PROPERLY DISPOSED'),
    (53, 'TOILET FACILITIES: PROPERLY CONSTRUCTED, SUPPLIED, & CLEANED'),
    (54, 'GARBAGE & REFUSE PROPERLY DISPOSED; FACILITIES MAINTAINED'),
    (55, 'PHYSICAL FACILITIES INSTALLED, MAINTAINED & CLEAN'),
    (56, 'ADEQUATE VENTILATION & LIGHTING'),
    (57, 'ALL FOOD EMPLOYEES HAVE FOOD HANDLER TRAINING'),
    (58, 'ALLERGEN TRAINING AS REQUIRED'),
    (59, 'PREVIOUS PRIORITY FOUNDATION VIOLATION CORRECTED'),
    (60, 'PREVIOUS CORE VIOLATION CORRECTED'),
    (61, 'SUMMARY REPORT DISPLAYED AND VISIBLE TO THE PUBLIC'),
    (62, 'COMPLIANCE WITH CLEAN INDOOR AIR ORDINANCE'),
    (63, 'REMOVAL OF SUSPENSION SIGN'),
    (64, 'MISCELLANEOUS / PUBLIC HEALTH ORDERS'),
    (70, 'NO SMOKING REGULATIONS');